#!/usr/bin/env python


"""
@PROJECT: proxy_twisted
@AUTHOR: momen
@TIME: 2/12/20 8:30 PM
"""

import logging
from proxy_twisted.https import Request
from lxml import etree
import weakref


logger = logging.getLogger(__name__)


class Spider(object):
    def __init__(self, engine, settings):
        logging.info('parser is starting...')
        self.setting = settings
        self.engine = weakref.ref(engine)

    @classmethod
    def produce(cls, engine, settings):
        return cls(engine, settings)

    def get_request(self, urls):
        for url in urls:
            yield Request(url, headers={'user-agent': ['Mozilla/5.0']}, callback=self.parse)

    def parse(self, response):
        logging.info('parsing...')
        return self._parse(response)

    def _parse(self, response):
        logging.debug(response.code)
        selector = etree.HTML(response.text)   # xml/html is formatted text generated by tree structural data, so...
        logging.debug(selector)
        nodes = selector.xpath(r'//table/tr')
        for node in nodes:
            result = node.xpath(r'td/text()|td/a/text()')
            logging.debug(result)
            if result:
                logging.debug('successfully get an item')
                yield result
